### ISSUE TITLE
Wrong characters

### ISSUE THREAD

**Issue by hieuhuynh93** [danielkwok21/s3-cloudfront-signedurl-medium#1]
Hi,
I found a mistake on your file, on the line of 35 (app.js), it must be a "cfFull**P**ath", not "cfFull**p**ath". Please modify it.
<img width="234" alt="Screen Shot 2022-07-05 at 09 52 18" src="https://user-images.githubusercontent.com/10773568/177240693-ddba95aa-e8d1-4330-b80b-97630ff9a2c5.png">

Btw, your example saved my time. Thank you.

**Comment by danielkwok21** [comment]
Hi @hieuhuynh93 !

Thanks for the feedback.
Modified https://github.com/danielkwok21/s3-cloudfront-signedurl-medium/blob/master/app.js#L35

Glad it help you.
